# Generated by Django 5.2 on 2025-04-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='profile',
            name='calorie_adjustment',
            field=models.IntegerField(default=0, verbose_name='Коррекция калорий'),
        ),
        migrations.AddField(
            model_name='profile',
            name='goal',
            field=models.CharField(choices=[('gain', 'Набор веса'), ('lose', 'Похудение')], default='maintain', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=160, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, default=60, verbose_name='Weight'),
        ),
    ]
