# Generated by Django 5.2 on 2025-04-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduleauth', '0006_weighthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(default=60.0, verbose_name='Weight'),
        ),
    ]
