# Generated by Django 5.2 on 2025-04-07 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ru_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proteins', models.FloatField(default=0)),
                ('fats', models.FloatField(default=0)),
                ('carbohydrates', models.FloatField(default=0)),
                ('caloricity', models.FloatField(default=0)),
                ('is_for_weight_main', models.BooleanField(default=False)),
                ('is_for_weight_gain', models.BooleanField(default=False)),
                ('is_for_weight_loss', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulerec.category')),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
    ]
